
# -------------------------------------------
#
#               /\_/\
#              ( o o )
# 	       ==_Y_==
#   	         `-'
# 
# -------------------------------------------
# Kitty Configuration - Tarun Bhandari
# -------------------------------------------


# getting the colorscheme from pywal16
# -------------------------------------------
include ~/.cache/wal/colors-kitty.conf

# fonts
# -------------------------------------------
font_family      "JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto

# font size
# -------------------------------------------
font_size 9.5

# hide windows decorations
# -------------------------------------------
hide_window_decorations yes

# padding
# -------------------------------------------
window_padding_width 5

# keys
# -------------------------------------------

# Tab
# -------------------------------------------
map ctrl+shift+t new_tab
map ctrl+shift+q close_tab
map ctrl+tab next_tab
map ctrl+shift+. move_tab_forward
map ctrl+shift+, move_tab_backward

# Windows
# -------------------------------------------
map ctrl+shift+enter new_window
# switch focus to next window
map ctrl+shift+] next_window
# switch focus to preivous window
map ctrl+shift+[ previous_window
map ctrl+shift+w close_window
map ctrl+shift+k move_window_forward
map ctrl+shift+j move_window_backward
# to move focus on specific windows use ctrl+shift+no to navigate to that windows


